'use strict';

const ORG_ID = 'Y2lzY29zcGFyazovL3VzL09SR0FOSVpBVElPTi9kZW1vb3Jn';

const LOCATIONS = [
  {
    id: 'loc-wacker-001',
    displayName: 'Wacker Drive HQ',
    orgId: ORG_ID,
    address: { street: '233 S Wacker Dr', city: 'Chicago', state: 'IL', postalCode: '60606', country: 'US' },
    floors: [
      { id: 'floor-wacker-10', locationId: 'loc-wacker-001', displayName: 'Floor 10', floorNumber: 10 },
      { id: 'floor-wacker-11', locationId: 'loc-wacker-001', displayName: 'Floor 11', floorNumber: 11 },
      { id: 'floor-wacker-12', locationId: 'loc-wacker-001', displayName: 'Floor 12', floorNumber: 12 },
    ],
    subnet: '10.10',
  },
  {
    id: 'loc-lasalle-001',
    displayName: 'LaSalle Office',
    orgId: ORG_ID,
    address: { street: '190 S LaSalle St', city: 'Chicago', state: 'IL', postalCode: '60603', country: 'US' },
    floors: [
      { id: 'floor-lasalle-5', locationId: 'loc-lasalle-001', displayName: 'Floor 5', floorNumber: 5 },
      { id: 'floor-lasalle-6', locationId: 'loc-lasalle-001', displayName: 'Floor 6', floorNumber: 6 },
    ],
    subnet: '10.20',
  },
  {
    id: 'loc-dublin-001',
    displayName: 'Dublin Office',
    orgId: ORG_ID,
    address: { street: '1 Grand Canal Square', city: 'Dublin', state: '', postalCode: 'D02 P820', country: 'IE' },
    floors: [
      { id: 'floor-dublin-1', locationId: 'loc-dublin-001', displayName: 'Floor 1', floorNumber: 1 },
      { id: 'floor-dublin-2', locationId: 'loc-dublin-001', displayName: 'Floor 2', floorNumber: 2 },
    ],
    subnet: '10.30',
  },
  {
    id: 'loc-miami-001',
    displayName: 'Miami Operations Center',
    orgId: ORG_ID,
    address: { street: '1200 Brickell Ave', city: 'Miami', state: 'FL', postalCode: '33131', country: 'US' },
    floors: [
      { id: 'floor-miami-3', locationId: 'loc-miami-001', displayName: 'Floor 3', floorNumber: 3 },
    ],
    subnet: '10.40',
  },
];

// Workspaces keyed by id
const WORKSPACES = [
  // --- Wacker Floor 10 ---
  { id: 'ws-wacker-exec', displayName: 'Executive Boardroom', locationId: 'loc-wacker-001', floorId: 'floor-wacker-10', type: 'boardRoom', capacity: 20, extension: '2001' },
  { id: 'ws-wacker-lakemich', displayName: 'Lake Michigan', locationId: 'loc-wacker-001', floorId: 'floor-wacker-10', type: 'meetingRoom', capacity: 12, extension: '2002' },
  { id: 'ws-wacker-loop', displayName: 'The Loop', locationId: 'loc-wacker-001', floorId: 'floor-wacker-10', type: 'meetingRoom', capacity: 8, extension: '2003' },
  { id: 'ws-wacker-huddle10a', displayName: 'Huddle 10A', locationId: 'loc-wacker-001', floorId: 'floor-wacker-10', type: 'focusRoom', capacity: 4, extension: '2004' },
  { id: 'ws-wacker-huddle10b', displayName: 'Huddle 10B', locationId: 'loc-wacker-001', floorId: 'floor-wacker-10', type: 'focusRoom', capacity: 4, extension: '2005' },
  { id: 'ws-wacker-lobby', displayName: 'Lobby Display - Wacker', locationId: 'loc-wacker-001', floorId: 'floor-wacker-10', type: 'other', capacity: 0, extension: '2006' },
  // --- Wacker Floor 11 ---
  { id: 'ws-wacker-millennium', displayName: 'Millennium Park', locationId: 'loc-wacker-001', floorId: 'floor-wacker-11', type: 'meetingRoom', capacity: 10, extension: '2101' },
  { id: 'ws-wacker-wrigley', displayName: 'Wrigley', locationId: 'loc-wacker-001', floorId: 'floor-wacker-11', type: 'meetingRoom', capacity: 8, extension: '2102' },
  { id: 'ws-wacker-navypier', displayName: 'Navy Pier', locationId: 'loc-wacker-001', floorId: 'floor-wacker-11', type: 'meetingRoom', capacity: 6, extension: '2103' },
  { id: 'ws-wacker-huddle11a', displayName: 'Huddle 11A', locationId: 'loc-wacker-001', floorId: 'floor-wacker-11', type: 'focusRoom', capacity: 4, extension: '2104' },
  { id: 'ws-wacker-townhall', displayName: 'Town Hall', locationId: 'loc-wacker-001', floorId: 'floor-wacker-11', type: 'other', capacity: 50, extension: '2105' },
  // --- Wacker Floor 12 ---
  { id: 'ws-wacker-trainnorth', displayName: 'Training Center North', locationId: 'loc-wacker-001', floorId: 'floor-wacker-12', type: 'meetingRoom', capacity: 30, extension: '2201' },
  { id: 'ws-wacker-trainsouth', displayName: 'Training Center South', locationId: 'loc-wacker-001', floorId: 'floor-wacker-12', type: 'meetingRoom', capacity: 30, extension: '2202' },
  { id: 'ws-wacker-boardrooma', displayName: 'Board Room A', locationId: 'loc-wacker-001', floorId: 'floor-wacker-12', type: 'boardRoom', capacity: 16, extension: '2203' },
  // --- LaSalle Floor 5 ---
  { id: 'ws-lasalle-focus5a', displayName: 'Focus Room 5A', locationId: 'loc-lasalle-001', floorId: 'floor-lasalle-5', type: 'focusRoom', capacity: 2, extension: '3001' },
  { id: 'ws-lasalle-focus5b', displayName: 'Focus Room 5B', locationId: 'loc-lasalle-001', floorId: 'floor-lasalle-5', type: 'focusRoom', capacity: 2, extension: '3002' },
  { id: 'ws-lasalle-confA', displayName: 'Conference A', locationId: 'loc-lasalle-001', floorId: 'floor-lasalle-5', type: 'meetingRoom', capacity: 8, extension: '3003' },
  { id: 'ws-lasalle-lobby', displayName: 'Lobby Display - LaSalle', locationId: 'loc-lasalle-001', floorId: 'floor-lasalle-5', type: 'other', capacity: 0, extension: '3004' },
  // --- LaSalle Floor 6 ---
  { id: 'ws-lasalle-confB', displayName: 'Conference B', locationId: 'loc-lasalle-001', floorId: 'floor-lasalle-6', type: 'meetingRoom', capacity: 10, extension: '3101' },
  { id: 'ws-lasalle-confC', displayName: 'Conference C', locationId: 'loc-lasalle-001', floorId: 'floor-lasalle-6', type: 'meetingRoom', capacity: 6, extension: '3102' },
  // --- Dublin Floor 1 ---
  { id: 'ws-dublin-liffey', displayName: 'Liffey', locationId: 'loc-dublin-001', floorId: 'floor-dublin-1', type: 'meetingRoom', capacity: 10, extension: '4001' },
  { id: 'ws-dublin-tembar', displayName: 'Temple Bar', locationId: 'loc-dublin-001', floorId: 'floor-dublin-1', type: 'meetingRoom', capacity: 8, extension: '4002' },
  { id: 'ws-dublin-allhands', displayName: 'All Hands Dublin', locationId: 'loc-dublin-001', floorId: 'floor-dublin-1', type: 'other', capacity: 40, extension: '4003' },
  // --- Dublin Floor 2 ---
  { id: 'ws-dublin-focus2a', displayName: 'Focus 2A', locationId: 'loc-dublin-001', floorId: 'floor-dublin-2', type: 'focusRoom', capacity: 2, extension: '4101' },
  { id: 'ws-dublin-conf2', displayName: 'Conference 2', locationId: 'loc-dublin-001', floorId: 'floor-dublin-2', type: 'meetingRoom', capacity: 8, extension: '4102' },
  // --- Miami Floor 3 ---
  { id: 'ws-miami-biscayne', displayName: 'Biscayne', locationId: 'loc-miami-001', floorId: 'floor-miami-3', type: 'meetingRoom', capacity: 12, extension: '5001' },
  { id: 'ws-miami-ops', displayName: 'Operations Center', locationId: 'loc-miami-001', floorId: 'floor-miami-3', type: 'meetingRoom', capacity: 20, extension: '5002' },
  { id: 'ws-miami-huddle', displayName: 'Huddle Miami', locationId: 'loc-miami-001', floorId: 'floor-miami-3', type: 'focusRoom', capacity: 4, extension: '5003' },
];

// Helper to look up location subnet for IP generation
const LOCATION_SUBNET = {};
for (const loc of LOCATIONS) {
  LOCATION_SUBNET[loc.id] = loc.subnet;
}

function ipForWorkspace(wsId, offset) {
  const ws = WORKSPACES.find(w => w.id === wsId);
  const subnet = LOCATION_SUBNET[ws?.locationId] || '10.99';
  return `${subnet}.${Math.floor(offset / 254) + 1}.${(offset % 254) + 2}`;
}

function macFromSerial(serial) {
  const hex = Buffer.from(serial).toString('hex').slice(0, 12).toUpperCase();
  return hex.match(/.{2}/g).join(':');
}

// Build devices list
// Each room system + paired Navigator where applicable
let ipOffset = 10;
function nextIp(wsId) { return ipForWorkspace(wsId, ipOffset++); }

const DEVICES = [
  // Wacker - Executive Boardroom (Room Kit EQ + Navigator)
  {
    id: 'dev-wacker-exec-eq',
    displayName: 'Executive Boardroom - Room Kit EQ',
    product: 'Cisco Room Kit EQ',
    productId: 'CS-ROOMKITEQ-K9',
    type: 'roomdesk',
    serial: 'FTT23450001',
    mac: 'A4:B1:C1:00:01:01',
    ip: '10.10.1.11',
    workspaceId: 'ws-wacker-exec',
    locationId: 'loc-wacker-001',
    firmware: 'ce11.21.1.4.a4c3a39',
    connectionStatus: 'connected',
    tags: ['boardroom', 'wacker', 'floor-10'],
  },
  {
    id: 'dev-wacker-exec-nav',
    displayName: 'Executive Boardroom - Navigator',
    product: 'Cisco Room Navigator',
    productId: 'CS-TOUCH10-K9',
    type: 'roomnavigator',
    serial: 'FTT23450002',
    mac: 'A4:B1:C1:00:01:02',
    ip: '10.10.1.12',
    workspaceId: 'ws-wacker-exec',
    locationId: 'loc-wacker-001',
    firmware: 'ce11.21.1.4.a4c3a39',
    connectionStatus: 'connected',
    tags: ['navigator', 'wacker', 'floor-10'],
  },
  // Wacker - Lake Michigan (Room Bar Pro + Navigator)
  {
    id: 'dev-wacker-lakemich-rbp',
    displayName: 'Lake Michigan - Room Bar Pro',
    product: 'Cisco Room Bar Pro',
    productId: 'CS-ROOMBAR-PRO-K9',
    type: 'roomdesk',
    serial: 'FTT23450003',
    mac: 'A4:B1:C1:00:02:01',
    ip: '10.10.1.13',
    workspaceId: 'ws-wacker-lakemich',
    locationId: 'loc-wacker-001',
    firmware: 'roomos11.20.1.7.6e71becef65',
    connectionStatus: 'connected',
    tags: ['conference', 'wacker', 'floor-10'],
  },
  {
    id: 'dev-wacker-lakemich-nav',
    displayName: 'Lake Michigan - Navigator',
    product: 'Cisco Room Navigator',
    productId: 'CS-TOUCH10-K9',
    type: 'roomnavigator',
    serial: 'FTT23450004',
    mac: 'A4:B1:C1:00:02:02',
    ip: '10.10.1.14',
    workspaceId: 'ws-wacker-lakemich',
    locationId: 'loc-wacker-001',
    firmware: 'roomos11.20.1.7.6e71becef65',
    connectionStatus: 'connected',
    tags: ['navigator', 'wacker', 'floor-10'],
  },
  // Wacker - The Loop (Room Bar)
  {
    id: 'dev-wacker-loop-rb',
    displayName: 'The Loop - Room Bar',
    product: 'Cisco Room Bar',
    productId: 'CS-ROOMBAR-K9',
    type: 'roomdesk',
    serial: 'FTT23450005',
    mac: 'A4:B1:C1:00:03:01',
    ip: '10.10.1.15',
    workspaceId: 'ws-wacker-loop',
    locationId: 'loc-wacker-001',
    firmware: 'roomos11.20.1.7.6e71becef65',
    connectionStatus: 'connected',
    tags: ['conference', 'wacker', 'floor-10'],
  },
  // Wacker - Huddle 10A (Desk Pro)
  {
    id: 'dev-wacker-hud10a-dp',
    displayName: 'Huddle 10A - Desk Pro',
    product: 'Cisco Desk Pro',
    productId: 'CS-DESKPRO-K9',
    type: 'roomdesk',
    serial: 'FTT23450006',
    mac: 'A4:B1:C1:00:04:01',
    ip: '10.10.1.16',
    workspaceId: 'ws-wacker-huddle10a',
    locationId: 'loc-wacker-001',
    firmware: 'roomos11.20.1.7.6e71becef65',
    connectionStatus: 'connected',
    tags: ['huddle', 'wacker', 'floor-10'],
  },
  // Wacker - Huddle 10B (Desk Pro) - disconnected
  {
    id: 'dev-wacker-hud10b-dp',
    displayName: 'Huddle 10B - Desk Pro',
    product: 'Cisco Desk Pro',
    productId: 'CS-DESKPRO-K9',
    type: 'roomdesk',
    serial: 'FTT23450007',
    mac: 'A4:B1:C1:00:05:01',
    ip: '10.10.1.17',
    workspaceId: 'ws-wacker-huddle10b',
    locationId: 'loc-wacker-001',
    firmware: 'roomos11.20.1.7.6e71becef65',
    connectionStatus: 'disconnected',
    tags: ['huddle', 'wacker', 'floor-10'],
  },
  // Wacker - Lobby (Room Bar)
  {
    id: 'dev-wacker-lobby-rb',
    displayName: 'Lobby Display - Wacker',
    product: 'Cisco Room Bar',
    productId: 'CS-ROOMBAR-K9',
    type: 'roomdesk',
    serial: 'FTT23450008',
    mac: 'A4:B1:C1:00:06:01',
    ip: '10.10.1.18',
    workspaceId: 'ws-wacker-lobby',
    locationId: 'loc-wacker-001',
    firmware: 'roomos11.20.1.7.6e71becef65',
    connectionStatus: 'connected',
    tags: ['lobby', 'signage', 'wacker', 'floor-10'],
  },
  // Wacker Floor 11 - Millennium Park (Room Bar Pro + Navigator)
  {
    id: 'dev-wacker-millennium-rbp',
    displayName: 'Millennium Park - Room Bar Pro',
    product: 'Cisco Room Bar Pro',
    productId: 'CS-ROOMBAR-PRO-K9',
    type: 'roomdesk',
    serial: 'FTT23450009',
    mac: 'A4:B1:C1:00:07:01',
    ip: '10.10.2.11',
    workspaceId: 'ws-wacker-millennium',
    locationId: 'loc-wacker-001',
    firmware: 'roomos11.20.1.7.6e71becef65',
    connectionStatus: 'connected',
    tags: ['conference', 'wacker', 'floor-11'],
  },
  {
    id: 'dev-wacker-millennium-nav',
    displayName: 'Millennium Park - Navigator',
    product: 'Cisco Room Navigator',
    productId: 'CS-TOUCH10-K9',
    type: 'roomnavigator',
    serial: 'FTT23450010',
    mac: 'A4:B1:C1:00:07:02',
    ip: '10.10.2.12',
    workspaceId: 'ws-wacker-millennium',
    locationId: 'loc-wacker-001',
    firmware: 'roomos11.20.1.7.6e71becef65',
    connectionStatus: 'connected',
    tags: ['navigator', 'wacker', 'floor-11'],
  },
  // Wacker - Wrigley (Room Bar)
  {
    id: 'dev-wacker-wrigley-rb',
    displayName: 'Wrigley - Room Bar',
    product: 'Cisco Room Bar',
    productId: 'CS-ROOMBAR-K9',
    type: 'roomdesk',
    serial: 'FTT23450011',
    mac: 'A4:B1:C1:00:08:01',
    ip: '10.10.2.13',
    workspaceId: 'ws-wacker-wrigley',
    locationId: 'loc-wacker-001',
    firmware: 'roomos11.20.1.7.6e71becef65',
    connectionStatus: 'connected_with_issues',
    tags: ['conference', 'wacker', 'floor-11'],
  },
  // Wacker - Navy Pier (Room Bar)
  {
    id: 'dev-wacker-navypier-rb',
    displayName: 'Navy Pier - Room Bar',
    product: 'Cisco Room Bar',
    productId: 'CS-ROOMBAR-K9',
    type: 'roomdesk',
    serial: 'FTT23450012',
    mac: 'A4:B1:C1:00:09:01',
    ip: '10.10.2.14',
    workspaceId: 'ws-wacker-navypier',
    locationId: 'loc-wacker-001',
    firmware: 'roomos11.20.1.7.6e71becef65',
    connectionStatus: 'connected',
    tags: ['conference', 'wacker', 'floor-11'],
  },
  // Wacker - Huddle 11A (Desk Pro)
  {
    id: 'dev-wacker-hud11a-dp',
    displayName: 'Huddle 11A - Desk Pro',
    product: 'Cisco Desk Pro',
    productId: 'CS-DESKPRO-K9',
    type: 'roomdesk',
    serial: 'FTT23450013',
    mac: 'A4:B1:C1:00:0A:01',
    ip: '10.10.2.15',
    workspaceId: 'ws-wacker-huddle11a',
    locationId: 'loc-wacker-001',
    firmware: 'roomos11.20.1.7.6e71becef65',
    connectionStatus: 'connected',
    tags: ['huddle', 'wacker', 'floor-11'],
  },
  // Wacker - Town Hall (Board Pro 75 + Navigator)
  {
    id: 'dev-wacker-townhall-bp',
    displayName: 'Town Hall - Board Pro 75',
    product: 'Cisco Board Pro 75',
    productId: 'CS-BOARD-PRO-75-K9',
    type: 'roomdesk',
    serial: 'FTT23450014',
    mac: 'A4:B1:C1:00:0B:01',
    ip: '10.10.2.16',
    workspaceId: 'ws-wacker-townhall',
    locationId: 'loc-wacker-001',
    firmware: 'roomos11.20.1.7.6e71becef65',
    connectionStatus: 'connected',
    tags: ['all-hands', 'wacker', 'floor-11'],
  },
  {
    id: 'dev-wacker-townhall-nav',
    displayName: 'Town Hall - Navigator',
    product: 'Cisco Room Navigator',
    productId: 'CS-TOUCH10-K9',
    type: 'roomnavigator',
    serial: 'FTT23450015',
    mac: 'A4:B1:C1:00:0B:02',
    ip: '10.10.2.17',
    workspaceId: 'ws-wacker-townhall',
    locationId: 'loc-wacker-001',
    firmware: 'roomos11.20.1.7.6e71becef65',
    connectionStatus: 'connected',
    tags: ['navigator', 'wacker', 'floor-11'],
  },
  // Wacker Floor 12 - Training Center North (Board Pro 75 x2)
  {
    id: 'dev-wacker-trainnorth-bp1',
    displayName: 'Training Center North - Board Pro 75 (Primary)',
    product: 'Cisco Board Pro 75',
    productId: 'CS-BOARD-PRO-75-K9',
    type: 'roomdesk',
    serial: 'FTT23450016',
    mac: 'A4:B1:C1:00:0C:01',
    ip: '10.10.3.11',
    workspaceId: 'ws-wacker-trainnorth',
    locationId: 'loc-wacker-001',
    firmware: 'roomos11.20.1.7.6e71becef65',
    connectionStatus: 'connected',
    tags: ['training', 'wacker', 'floor-12'],
  },
  {
    id: 'dev-wacker-trainnorth-nav',
    displayName: 'Training Center North - Navigator',
    product: 'Cisco Room Navigator',
    productId: 'CS-TOUCH10-K9',
    type: 'roomnavigator',
    serial: 'FTT23450017',
    mac: 'A4:B1:C1:00:0C:02',
    ip: '10.10.3.12',
    workspaceId: 'ws-wacker-trainnorth',
    locationId: 'loc-wacker-001',
    firmware: 'roomos11.20.1.7.6e71becef65',
    connectionStatus: 'connected',
    tags: ['navigator', 'wacker', 'floor-12'],
  },
  // Wacker - Training Center South (Board Pro 75)
  {
    id: 'dev-wacker-trainsouth-bp',
    displayName: 'Training Center South - Board Pro 75',
    product: 'Cisco Board Pro 75',
    productId: 'CS-BOARD-PRO-75-K9',
    type: 'roomdesk',
    serial: 'FTT23450018',
    mac: 'A4:B1:C1:00:0D:01',
    ip: '10.10.3.13',
    workspaceId: 'ws-wacker-trainsouth',
    locationId: 'loc-wacker-001',
    firmware: 'roomos11.20.1.7.6e71becef65',
    connectionStatus: 'connected',
    tags: ['training', 'wacker', 'floor-12'],
  },
  // Wacker - Board Room A (Room Kit EQ + Navigator)
  {
    id: 'dev-wacker-boardrooma-eq',
    displayName: 'Board Room A - Room Kit EQ',
    product: 'Cisco Room Kit EQ',
    productId: 'CS-ROOMKITEQ-K9',
    type: 'roomdesk',
    serial: 'FTT23450019',
    mac: 'A4:B1:C1:00:0E:01',
    ip: '10.10.3.14',
    workspaceId: 'ws-wacker-boardrooma',
    locationId: 'loc-wacker-001',
    firmware: 'ce11.21.1.4.a4c3a39',
    connectionStatus: 'connected',
    tags: ['boardroom', 'wacker', 'floor-12'],
  },
  {
    id: 'dev-wacker-boardrooma-nav',
    displayName: 'Board Room A - Navigator',
    product: 'Cisco Room Navigator',
    productId: 'CS-TOUCH10-K9',
    type: 'roomnavigator',
    serial: 'FTT23450020',
    mac: 'A4:B1:C1:00:0E:02',
    ip: '10.10.3.15',
    workspaceId: 'ws-wacker-boardrooma',
    locationId: 'loc-wacker-001',
    firmware: 'ce11.21.1.4.a4c3a39',
    connectionStatus: 'connected',
    tags: ['navigator', 'wacker', 'floor-12'],
  },
  // LaSalle - Focus Room 5A (Desk Pro)
  {
    id: 'dev-lasalle-focus5a-dp',
    displayName: 'Focus Room 5A - Desk Pro',
    product: 'Cisco Desk Pro',
    productId: 'CS-DESKPRO-K9',
    type: 'roomdesk',
    serial: 'FTT23450021',
    mac: 'A4:B2:C2:00:01:01',
    ip: '10.20.1.11',
    workspaceId: 'ws-lasalle-focus5a',
    locationId: 'loc-lasalle-001',
    firmware: 'roomos11.20.1.7.6e71becef65',
    connectionStatus: 'connected',
    tags: ['focus', 'lasalle', 'floor-5'],
  },
  // LaSalle - Focus Room 5B (Desk Pro) - connected_with_issues
  {
    id: 'dev-lasalle-focus5b-dp',
    displayName: 'Focus Room 5B - Desk Pro',
    product: 'Cisco Desk Pro',
    productId: 'CS-DESKPRO-K9',
    type: 'roomdesk',
    serial: 'FTT23450022',
    mac: 'A4:B2:C2:00:02:01',
    ip: '10.20.1.12',
    workspaceId: 'ws-lasalle-focus5b',
    locationId: 'loc-lasalle-001',
    firmware: 'roomos11.20.1.7.6e71becef65',
    connectionStatus: 'connected_with_issues',
    tags: ['focus', 'lasalle', 'floor-5'],
  },
  // LaSalle - Conference A (Room Bar Pro + Navigator)
  {
    id: 'dev-lasalle-confA-rbp',
    displayName: 'Conference A - Room Bar Pro',
    product: 'Cisco Room Bar Pro',
    productId: 'CS-ROOMBAR-PRO-K9',
    type: 'roomdesk',
    serial: 'FTT23450023',
    mac: 'A4:B2:C2:00:03:01',
    ip: '10.20.1.13',
    workspaceId: 'ws-lasalle-confA',
    locationId: 'loc-lasalle-001',
    firmware: 'roomos11.20.1.7.6e71becef65',
    connectionStatus: 'connected',
    tags: ['conference', 'lasalle', 'floor-5'],
  },
  {
    id: 'dev-lasalle-confA-nav',
    displayName: 'Conference A - Navigator',
    product: 'Cisco Room Navigator',
    productId: 'CS-TOUCH10-K9',
    type: 'roomnavigator',
    serial: 'FTT23450024',
    mac: 'A4:B2:C2:00:03:02',
    ip: '10.20.1.14',
    workspaceId: 'ws-lasalle-confA',
    locationId: 'loc-lasalle-001',
    firmware: 'roomos11.20.1.7.6e71becef65',
    connectionStatus: 'connected',
    tags: ['navigator', 'lasalle', 'floor-5'],
  },
  // LaSalle - Lobby (Room Bar)
  {
    id: 'dev-lasalle-lobby-rb',
    displayName: 'Lobby Display - LaSalle',
    product: 'Cisco Room Bar',
    productId: 'CS-ROOMBAR-K9',
    type: 'roomdesk',
    serial: 'FTT23450025',
    mac: 'A4:B2:C2:00:04:01',
    ip: '10.20.1.15',
    workspaceId: 'ws-lasalle-lobby',
    locationId: 'loc-lasalle-001',
    firmware: 'roomos11.20.1.7.6e71becef65',
    connectionStatus: 'connected',
    tags: ['lobby', 'signage', 'lasalle', 'floor-5'],
  },
  // LaSalle Floor 6 - Conference B (Room Bar Pro + Navigator)
  {
    id: 'dev-lasalle-confB-rbp',
    displayName: 'Conference B - Room Bar Pro',
    product: 'Cisco Room Bar Pro',
    productId: 'CS-ROOMBAR-PRO-K9',
    type: 'roomdesk',
    serial: 'FTT23450026',
    mac: 'A4:B2:C2:00:05:01',
    ip: '10.20.2.11',
    workspaceId: 'ws-lasalle-confB',
    locationId: 'loc-lasalle-001',
    firmware: 'roomos11.20.1.7.6e71becef65',
    connectionStatus: 'connected',
    tags: ['conference', 'lasalle', 'floor-6'],
  },
  {
    id: 'dev-lasalle-confB-nav',
    displayName: 'Conference B - Navigator',
    product: 'Cisco Room Navigator',
    productId: 'CS-TOUCH10-K9',
    type: 'roomnavigator',
    serial: 'FTT23450027',
    mac: 'A4:B2:C2:00:05:02',
    ip: '10.20.2.12',
    workspaceId: 'ws-lasalle-confB',
    locationId: 'loc-lasalle-001',
    firmware: 'roomos11.20.1.7.6e71becef65',
    connectionStatus: 'connected',
    tags: ['navigator', 'lasalle', 'floor-6'],
  },
  // LaSalle - Conference C (Room Bar) - disconnected
  {
    id: 'dev-lasalle-confC-rb',
    displayName: 'Conference C - Room Bar',
    product: 'Cisco Room Bar',
    productId: 'CS-ROOMBAR-K9',
    type: 'roomdesk',
    serial: 'FTT23450028',
    mac: 'A4:B2:C2:00:06:01',
    ip: '10.20.2.13',
    workspaceId: 'ws-lasalle-confC',
    locationId: 'loc-lasalle-001',
    firmware: 'roomos11.20.1.7.6e71becef65',
    connectionStatus: 'disconnected',
    tags: ['conference', 'lasalle', 'floor-6'],
  },
  // Dublin Floor 1 - Liffey (Room Bar Pro + Navigator)
  {
    id: 'dev-dublin-liffey-rbp',
    displayName: 'Liffey - Room Bar Pro',
    product: 'Cisco Room Bar Pro',
    productId: 'CS-ROOMBAR-PRO-K9',
    type: 'roomdesk',
    serial: 'FTT23450029',
    mac: 'A4:B3:C3:00:01:01',
    ip: '10.30.1.11',
    workspaceId: 'ws-dublin-liffey',
    locationId: 'loc-dublin-001',
    firmware: 'roomos11.20.1.7.6e71becef65',
    connectionStatus: 'connected',
    tags: ['conference', 'dublin', 'floor-1'],
  },
  {
    id: 'dev-dublin-liffey-nav',
    displayName: 'Liffey - Navigator',
    product: 'Cisco Room Navigator',
    productId: 'CS-TOUCH10-K9',
    type: 'roomnavigator',
    serial: 'FTT23450030',
    mac: 'A4:B3:C3:00:01:02',
    ip: '10.30.1.12',
    workspaceId: 'ws-dublin-liffey',
    locationId: 'loc-dublin-001',
    firmware: 'roomos11.20.1.7.6e71becef65',
    connectionStatus: 'connected',
    tags: ['navigator', 'dublin', 'floor-1'],
  },
  // Dublin - Temple Bar (Room Bar)
  {
    id: 'dev-dublin-tembar-rb',
    displayName: 'Temple Bar - Room Bar',
    product: 'Cisco Room Bar',
    productId: 'CS-ROOMBAR-K9',
    type: 'roomdesk',
    serial: 'FTT23450031',
    mac: 'A4:B3:C3:00:02:01',
    ip: '10.30.1.13',
    workspaceId: 'ws-dublin-tembar',
    locationId: 'loc-dublin-001',
    firmware: 'roomos11.20.1.7.6e71becef65',
    connectionStatus: 'connected',
    tags: ['conference', 'dublin', 'floor-1'],
  },
  // Dublin - All Hands (Board Pro 75 + Navigator)
  {
    id: 'dev-dublin-allhands-bp',
    displayName: 'All Hands Dublin - Board Pro 75',
    product: 'Cisco Board Pro 75',
    productId: 'CS-BOARD-PRO-75-K9',
    type: 'roomdesk',
    serial: 'FTT23450032',
    mac: 'A4:B3:C3:00:03:01',
    ip: '10.30.1.14',
    workspaceId: 'ws-dublin-allhands',
    locationId: 'loc-dublin-001',
    firmware: 'roomos11.20.1.7.6e71becef65',
    connectionStatus: 'connected',
    tags: ['all-hands', 'dublin', 'floor-1'],
  },
  {
    id: 'dev-dublin-allhands-nav',
    displayName: 'All Hands Dublin - Navigator',
    product: 'Cisco Room Navigator',
    productId: 'CS-TOUCH10-K9',
    type: 'roomnavigator',
    serial: 'FTT23450033',
    mac: 'A4:B3:C3:00:03:02',
    ip: '10.30.1.15',
    workspaceId: 'ws-dublin-allhands',
    locationId: 'loc-dublin-001',
    firmware: 'roomos11.20.1.7.6e71becef65',
    connectionStatus: 'connected',
    tags: ['navigator', 'dublin', 'floor-1'],
  },
  // Dublin Floor 2 - Focus 2A (Desk Pro)
  {
    id: 'dev-dublin-focus2a-dp',
    displayName: 'Focus 2A - Desk Pro',
    product: 'Cisco Desk Pro',
    productId: 'CS-DESKPRO-K9',
    type: 'roomdesk',
    serial: 'FTT23450034',
    mac: 'A4:B3:C3:00:04:01',
    ip: '10.30.2.11',
    workspaceId: 'ws-dublin-focus2a',
    locationId: 'loc-dublin-001',
    firmware: 'roomos11.20.1.7.6e71becef65',
    connectionStatus: 'connected',
    tags: ['focus', 'dublin', 'floor-2'],
  },
  // Dublin - Conference 2 (Room Bar Pro + Navigator)
  {
    id: 'dev-dublin-conf2-rbp',
    displayName: 'Conference 2 - Room Bar Pro',
    product: 'Cisco Room Bar Pro',
    productId: 'CS-ROOMBAR-PRO-K9',
    type: 'roomdesk',
    serial: 'FTT23450035',
    mac: 'A4:B3:C3:00:05:01',
    ip: '10.30.2.12',
    workspaceId: 'ws-dublin-conf2',
    locationId: 'loc-dublin-001',
    firmware: 'roomos11.20.1.7.6e71becef65',
    connectionStatus: 'connected',
    tags: ['conference', 'dublin', 'floor-2'],
  },
  {
    id: 'dev-dublin-conf2-nav',
    displayName: 'Conference 2 - Navigator',
    product: 'Cisco Room Navigator',
    productId: 'CS-TOUCH10-K9',
    type: 'roomnavigator',
    serial: 'FTT23450036',
    mac: 'A4:B3:C3:00:05:02',
    ip: '10.30.2.13',
    workspaceId: 'ws-dublin-conf2',
    locationId: 'loc-dublin-001',
    firmware: 'roomos11.20.1.7.6e71becef65',
    connectionStatus: 'connected',
    tags: ['navigator', 'dublin', 'floor-2'],
  },
  // Miami Floor 3 - Biscayne (Room Kit EQ + Navigator)
  {
    id: 'dev-miami-biscayne-eq',
    displayName: 'Biscayne - Room Kit EQ',
    product: 'Cisco Room Kit EQ',
    productId: 'CS-ROOMKITEQ-K9',
    type: 'roomdesk',
    serial: 'FTT23450037',
    mac: 'A4:B4:C4:00:01:01',
    ip: '10.40.1.11',
    workspaceId: 'ws-miami-biscayne',
    locationId: 'loc-miami-001',
    firmware: 'ce11.21.1.4.a4c3a39',
    connectionStatus: 'connected',
    tags: ['conference', 'miami', 'floor-3'],
  },
  {
    id: 'dev-miami-biscayne-nav',
    displayName: 'Biscayne - Navigator',
    product: 'Cisco Room Navigator',
    productId: 'CS-TOUCH10-K9',
    type: 'roomnavigator',
    serial: 'FTT23450038',
    mac: 'A4:B4:C4:00:01:02',
    ip: '10.40.1.12',
    workspaceId: 'ws-miami-biscayne',
    locationId: 'loc-miami-001',
    firmware: 'ce11.21.1.4.a4c3a39',
    connectionStatus: 'connected',
    tags: ['navigator', 'miami', 'floor-3'],
  },
  // Miami - Operations Center (Board Pro 75 + Navigator)
  {
    id: 'dev-miami-ops-bp',
    displayName: 'Operations Center - Board Pro 75',
    product: 'Cisco Board Pro 75',
    productId: 'CS-BOARD-PRO-75-K9',
    type: 'roomdesk',
    serial: 'FTT23450039',
    mac: 'A4:B4:C4:00:02:01',
    ip: '10.40.1.13',
    workspaceId: 'ws-miami-ops',
    locationId: 'loc-miami-001',
    firmware: 'roomos11.20.1.7.6e71becef65',
    connectionStatus: 'connected',
    tags: ['operations', 'miami', 'floor-3'],
  },
  {
    id: 'dev-miami-ops-nav',
    displayName: 'Operations Center - Navigator',
    product: 'Cisco Room Navigator',
    productId: 'CS-TOUCH10-K9',
    type: 'roomnavigator',
    serial: 'FTT23450040',
    mac: 'A4:B4:C4:00:02:02',
    ip: '10.40.1.14',
    workspaceId: 'ws-miami-ops',
    locationId: 'loc-miami-001',
    firmware: 'roomos11.20.1.7.6e71becef65',
    connectionStatus: 'connected',
    tags: ['navigator', 'miami', 'floor-3'],
  },
  // Miami - Huddle (Desk Pro)
  {
    id: 'dev-miami-huddle-dp',
    displayName: 'Huddle Miami - Desk Pro',
    product: 'Cisco Desk Pro',
    productId: 'CS-DESKPRO-K9',
    type: 'roomdesk',
    serial: 'FTT23450041',
    mac: 'A4:B4:C4:00:03:01',
    ip: '10.40.1.15',
    workspaceId: 'ws-miami-huddle',
    locationId: 'loc-miami-001',
    firmware: 'roomos11.20.1.7.6e71becef65',
    connectionStatus: 'connected',
    tags: ['huddle', 'miami', 'floor-3'],
  },
];

// Device configs keyed by deviceId
function buildDeviceConfig(device) {
  const isNavigator = device.type === 'roomnavigator';
  return {
    deviceId: device.id,
    items: [
      { key: 'Audio.DefaultVolume', value: '50', valueType: 'Integer', source: 'default' },
      { key: 'Audio.MaxVolume', value: '90', valueType: 'Integer', source: 'default' },
      { key: 'Audio.Ultrasound.MaxVolume', value: '70', valueType: 'Integer', source: 'custom' },
      ...(isNavigator ? [] : [
        { key: 'Video.Monitors', value: 'Single', valueType: 'String', source: 'default' },
        { key: 'Video.DefaultPresentationSource', value: '2', valueType: 'Integer', source: 'default' },
        { key: 'Video.Selfview.Default.Mode', value: 'Current', valueType: 'String', source: 'default' },
      ]),
      { key: 'Network.DNS.Server.1.Address', value: '10.0.0.1', valueType: 'String', source: 'custom' },
      { key: 'Network.NTP.Server.1.Address', value: 'pool.ntp.org', valueType: 'String', source: 'default' },
      { key: 'NetworkServices.CDP.Mode', value: 'On', valueType: 'String', source: 'default' },
      { key: 'UserInterface.Language', value: 'English', valueType: 'String', source: 'default' },
      { key: 'UserInterface.OSD.Mode', value: 'Auto', valueType: 'String', source: 'default' },
      { key: 'UserInterface.Branding.AwakeBranding.Colors', value: 'Auto', valueType: 'String', source: 'default' },
    ],
  };
}

// xAPI status responses keyed by deviceId
function buildXapiStatus(device) {
  const uptime = Math.floor(Math.random() * 30 * 86400) + 86400; // 1-30 days in seconds
  return {
    DeviceId: device.id,
    SystemUnit: {
      Hardware: { Module: { SerialNumber: device.serial } },
      Software: { Version: device.firmware, Name: 'RoomOS', ReleaseDate: '2024-11-15' },
      Uptime: uptime,
      State: { System: device.connectionStatus === 'connected' ? 'Initialized' : 'Error' },
    },
    Network: [
      {
        id: '1',
        IPv4: { Address: device.ip, SubnetMask: '255.255.255.0', Gateway: device.ip.replace(/\.\d+$/, '.1') },
        DNS: { Domain: { Name: 'corp.example.com' } },
        Ethernet: { MacAddress: device.mac, Speed: '1000full' },
      },
    ],
    Audio: { Volume: 50 },
    Standby: { State: 'Standby', Delay: 10 },
    Call: [],
    Cameras: { Camera: device.type !== 'roomnavigator' ? [{ id: '1', Connected: 'True', Model: device.product }] : [] },
    Peripherals: {
      ConnectedDevice: device.type !== 'roomnavigator'
        ? [{ id: '1', Name: `${device.displayName} - Navigator`, Type: 'TouchPanel', Status: 'Connected' }]
        : [],
    },
  };
}

// Build the workspace response matching Control Hub API shape
function enrichWorkspace(ws) {
  const loc = LOCATIONS.find(l => l.id === ws.locationId);
  const floor = loc?.floors.find(f => f.id === ws.floorId);
  return {
    id: ws.id,
    orgId: ORG_ID,
    displayName: ws.displayName,
    type: ws.type,
    capacity: ws.capacity,
    locationId: ws.locationId,
    floorId: ws.floorId,
    location: {
      id: ws.locationId,
      displayName: loc?.displayName,
      address: loc?.address,
    },
    floor: floor ? { id: floor.id, displayName: floor.displayName, floorNumber: floor.floorNumber } : null,
    calling: {
      type: 'webexCalling',
      webexCalling: { extension: ws.extension, locationId: ws.locationId },
    },
    calendar: { type: ws.capacity > 0 ? 'microsoft' : 'none' },
    sipAddress: `${ws.extension}@corp.example.com`,
    notes: null,
    created: '2024-01-15T08:00:00.000Z',
  };
}

// Build the device response matching Control Hub API shape
function enrichDevice(dev) {
  const ws = WORKSPACES.find(w => w.id === dev.workspaceId);
  const loc = LOCATIONS.find(l => l.id === dev.locationId);
  return {
    id: dev.id,
    displayName: dev.displayName,
    orgId: ORG_ID,
    workspaceId: dev.workspaceId,
    locationId: dev.locationId,
    product: dev.product,
    productId: dev.productId,
    type: dev.type,
    serial: dev.serial,
    mac: dev.mac,
    ip: dev.ip,
    activeInterface: 'Ethernet',
    software: { releaseChannel: 'stable', version: dev.firmware },
    firmware: dev.firmware,
    upgradeChannel: 'stable',
    connectionStatus: dev.connectionStatus,
    errorCodes: dev.connectionStatus === 'connected_with_issues' ? ['CONFIG_MISMATCH'] : [],
    capabilities: { configured: [] },
    permissions: { configured: [] },
    tags: dev.tags,
    workspaceName: ws?.displayName || null,
    locationName: loc?.displayName || null,
    created: '2024-01-15T08:00:00.000Z',
    lastSeen: new Date(Date.now() - Math.floor(Math.random() * 3600000)).toISOString(),
  };
}

module.exports = {
  ORG_ID,
  LOCATIONS,
  WORKSPACES,
  DEVICES,
  buildDeviceConfig,
  buildXapiStatus,
  enrichWorkspace,
  enrichDevice,
};
