-- APEX Field Ops Demo Data v3
-- Types: installation, service, site_survey, inspection, commissioning, training, event, cre_visit, network
DELETE FROM fieldops;

-- ============================================================
-- COMPLETED - Past 3 months
-- ============================================================

-- Oakbrook HQ Boardroom (WTB_DEMO_001) - Full project lifecycle
INSERT INTO fieldops (project_id, task_name, project_name, type, location, scheduled_date, start_time, end_time, assignee, status, notes, estimated_duration, completed_at, completed_by) VALUES
('WTB_DEMO_001', 'Site survey - 3rd floor boardroom', 'Oakbrook HQ - Executive Boardroom AV Install', 'site_survey', '2100 Spring Road, Oakbrook, IL 60523 - 3rd Floor', NOW() - INTERVAL '140 days', '9:00 AM', '1:00 PM', 'Mike Chen', 'completed', 'Walkthrough with AVI-SPL. Confirmed ceiling height 12ft, identified 4 conduit paths, verified power at rack location. Took photos of existing infrastructure.', 240, NOW() - INTERVAL '140 days', 'Mike Chen'),
('WTB_DEMO_001', 'CRE coordination - verify conduit rough-in', 'Oakbrook HQ - Executive Boardroom AV Install', 'cre_visit', '2100 Spring Road, Oakbrook, IL 60523 - 3rd Floor', NOW() - INTERVAL '95 days', '10:00 AM', '11:30 AM', 'Damon Alexander', 'completed', 'Met with Turner Construction PM on site. Conduit 80% complete. Discussed ceiling grid timeline - on track for dust-free by Jan 15.', 90, NOW() - INTERVAL '95 days', 'Damon Alexander'),
('WTB_DEMO_001', 'Network team - AV VLAN and switch config', 'Oakbrook HQ - Executive Boardroom AV Install', 'network', '2100 Spring Road, Oakbrook, IL 60523 - 3rd Floor IDF', NOW() - INTERVAL '66 days', '9:00 AM', '11:00 AM', 'Network Team (Jake Willis)', 'completed', 'Configured AV VLAN on IDF switch. Added 6 ports for AV devices. Verified PoE budget sufficient for Cisco Room Kit Pro.', 120, NOW() - INTERVAL '66 days', 'Jake Willis'),
('WTB_DEMO_001', 'Pre-install inspection - room readiness', 'Oakbrook HQ - Executive Boardroom AV Install', 'inspection', '2100 Spring Road, Oakbrook, IL 60523 - 3rd Floor', NOW() - INTERVAL '52 days', '9:00 AM', '11:00 AM', 'Damon Alexander', 'completed', 'Room dust-free confirmed. Paint complete, carpet laid, furniture in place. Conduit terminated at rack location. Ready for equipment.', 120, NOW() - INTERVAL '52 days', 'Damon Alexander'),
('WTB_DEMO_001', 'AVI-SPL installation (Day 1 of 4)', 'Oakbrook HQ - Executive Boardroom AV Install', 'installation', '2100 Spring Road, Oakbrook, IL 60523 - 3rd Floor', NOW() - INTERVAL '50 days', '7:00 AM', '5:00 PM', 'AVI-SPL (3 techs)', 'completed', 'Day 1: Rack build, display mounting, cable pulling. AVI-SPL team: Carlos, Brian, Andre.', 600, NOW() - INTERVAL '50 days', 'AVI-SPL'),
('WTB_DEMO_001', 'AVI-SPL installation (Day 2 of 4)', 'Oakbrook HQ - Executive Boardroom AV Install', 'installation', '2100 Spring Road, Oakbrook, IL 60523 - 3rd Floor', NOW() - INTERVAL '49 days', '7:00 AM', '5:00 PM', 'AVI-SPL (3 techs)', 'completed', 'Day 2: Crestron CP4 install, DM NVX endpoints, ceiling mic array mounting.', 600, NOW() - INTERVAL '49 days', 'AVI-SPL'),
('WTB_DEMO_001', 'AVI-SPL installation (Day 3 of 4)', 'Oakbrook HQ - Executive Boardroom AV Install', 'installation', '2100 Spring Road, Oakbrook, IL 60523 - 3rd Floor', NOW() - INTERVAL '48 days', '7:00 AM', '5:00 PM', 'AVI-SPL (3 techs)', 'completed', 'Day 3: Cisco Room Kit Pro install, programming begins, cable termination.', 600, NOW() - INTERVAL '48 days', 'AVI-SPL'),
('WTB_DEMO_001', 'AVI-SPL installation (Day 4 - commissioning)', 'Oakbrook HQ - Executive Boardroom AV Install', 'commissioning', '2100 Spring Road, Oakbrook, IL 60523 - 3rd Floor', NOW() - INTERVAL '47 days', '7:00 AM', '3:00 PM', 'AVI-SPL (3 techs)', 'completed', 'Day 4: Crestron programming loaded, DSP tuning, system integration testing with AVI-SPL programmer.', 480, NOW() - INTERVAL '47 days', 'AVI-SPL'),
('WTB_DEMO_001', 'AV team verification and UC testing', 'Oakbrook HQ - Executive Boardroom AV Install', 'commissioning', '2100 Spring Road, Oakbrook, IL 60523 - 3rd Floor', NOW() - INTERVAL '42 days', '9:00 AM', '3:00 PM', 'Damon Alexander', 'completed', 'Tested Webex (passed), Teams (passed), Zoom (failed - firewall rule needed, escalated, resolved same day). Audio tuning verified across 4 mic zones. Camera framing adjusted.', 360, NOW() - INTERVAL '42 days', 'Damon Alexander'),
('WTB_DEMO_001', 'Labeling and documentation walkthrough', 'Oakbrook HQ - Executive Boardroom AV Install', 'inspection', '2100 Spring Road, Oakbrook, IL 60523 - 3rd Floor', NOW() - INTERVAL '33 days', '9:00 AM', '12:00 PM', 'Mike Chen', 'completed', 'Labeled all cables, rack components, wall plates per standard. Took final photos for documentation.', 180, NOW() - INTERVAL '33 days', 'Mike Chen'),
('WTB_DEMO_001', 'Executive team AV training', 'Oakbrook HQ - Executive Boardroom AV Install', 'training', '2100 Spring Road, Oakbrook, IL 60523 - 3rd Floor', NOW() - INTERVAL '28 days', '10:00 AM', '12:00 PM', 'Damon Alexander', 'completed', 'Trained VP Operations and 6 exec assistants on touch panel, wireless sharing, camera controls. Left quick reference cards.', 120, NOW() - INTERVAL '28 days', 'Damon Alexander'),

-- Naperville Drive-Thru (WTB_DEMO_002)
('WTB_DEMO_002', 'Site survey - existing drive-thru system', 'Naperville Branch - Drive-Thru AV Upgrade', 'site_survey', '455 W Ogden Ave, Naperville, IL 60540', NOW() - INTERVAL '100 days', '9:00 AM', '12:00 PM', 'Mike Chen', 'completed', 'Documented 4 analog camera positions, 3 intercom stations, existing cabling runs. Noted PoE switch has 8 available ports.', 180, NOW() - INTERVAL '100 days', 'Mike Chen'),
('WTB_DEMO_002', 'Network team - PoE verification', 'Naperville Branch - Drive-Thru AV Upgrade', 'network', '455 W Ogden Ave, Naperville, IL 60540 - MDF', NOW() - INTERVAL '56 days', '9:00 AM', '10:30 AM', 'Network Team (Jake Willis)', 'completed', 'Verified PoE budget on access switch. 7 ports needed (4 cameras, 3 intercoms). Budget sufficient. Added to monitoring.', 90, NOW() - INTERVAL '56 days', 'Jake Willis'),
('WTB_DEMO_002', 'Whitlock Group installation', 'Naperville Branch - Drive-Thru AV Upgrade', 'installation', '455 W Ogden Ave, Naperville, IL 60540', NOW() - INTERVAL '52 days', '7:00 AM', '4:00 PM', 'Whitlock Group (2 techs)', 'completed', 'Removed analog system. Installed 4 Axis cameras and 3 Zenitel IP intercoms. Tested teller station integration.', 540, NOW() - INTERVAL '51 days', 'Whitlock Group'),
('WTB_DEMO_002', 'Verification and teller training', 'Naperville Branch - Drive-Thru AV Upgrade', 'training', '455 W Ogden Ave, Naperville, IL 60540', NOW() - INTERVAL '49 days', '9:00 AM', '11:00 AM', 'Damon Alexander', 'completed', 'Verified all camera angles with branch manager. Trained 8 tellers on new intercom controls.', 120, NOW() - INTERVAL '49 days', 'Damon Alexander'),

-- Beverly PA System (WTB_DEMO_003)
('WTB_DEMO_003', 'AVI-SPL speaker installation (3 days)', 'Beverly Branch - Emergency PA System Install', 'installation', '10250 S Western Ave, Chicago, IL 60643', NOW() - INTERVAL '70 days', '7:00 AM', '5:00 PM', 'AVI-SPL (2 techs)', 'completed', 'Installed Atlas Sound IP speakers across 12 zones. Ran Cat6 to each location. Compliance-driven fast track.', 600, NOW() - INTERVAL '66 days', 'AVI-SPL'),
('WTB_DEMO_003', 'Building automation integration', 'Beverly Branch - Emergency PA System Install', 'commissioning', '10250 S Western Ave, Chicago, IL 60643', NOW() - INTERVAL '64 days', '9:00 AM', '3:00 PM', 'Mike Chen', 'completed', 'Integrated PA system with BAS for emergency triggers. Tested fire alarm interface.', 360, NOW() - INTERVAL '64 days', 'Mike Chen'),
('WTB_DEMO_003', 'Full system test - all 12 zones', 'Beverly Branch - Emergency PA System Install', 'commissioning', '10250 S Western Ave, Chicago, IL 60643', NOW() - INTERVAL '61 days', '9:00 AM', '12:00 PM', 'Damon Alexander', 'completed', 'Tested each zone individually and all-call. Volume levels calibrated. Compliance officer present for sign-off.', 180, NOW() - INTERVAL '61 days', 'Damon Alexander'),

-- Schaumburg Buildout (WTB_DEMO_004) - completed visits
('WTB_DEMO_004', 'Site survey - 3 conference rooms (with AVI-SPL)', 'Schaumburg Branch - Conference Room Buildout', 'site_survey', '1400 E Golf Rd, Schaumburg, IL 60173', NOW() - INTERVAL '35 days', '9:00 AM', '1:00 PM', 'Mike Chen', 'completed', 'Surveyed Room A (12-seat), Room B (8-seat), Room C (huddle). Room A needs additional conduit run from IDF. Gensler plans reviewed on site.', 240, NOW() - INTERVAL '35 days', 'Mike Chen'),
('WTB_DEMO_004', 'CRE coordination - OAC Meeting #1', 'Schaumburg Branch - Conference Room Buildout', 'cre_visit', '1400 E Golf Rd, Schaumburg, IL 60173', NOW() - INTERVAL '38 days', '2:00 PM', '3:30 PM', 'Damon Alexander', 'completed', 'First OAC with Pepper Construction PM and Gensler architect. Presented AV infrastructure requirements. GC confirmed conduit timeline.', 90, NOW() - INTERVAL '38 days', 'Damon Alexander'),
('WTB_DEMO_004', 'CRE coordination - OAC Meeting #2', 'Schaumburg Branch - Conference Room Buildout', 'cre_visit', '1400 E Golf Rd, Schaumburg, IL 60173', NOW() - INTERVAL '10 days', '2:00 PM', '3:30 PM', 'Damon Alexander', 'completed', 'Conduit 70% complete. Room A ceiling grid delayed 1 week. Pepper PM adjusting schedule. No impact to AV timeline yet.', 90, NOW() - INTERVAL '10 days', 'Damon Alexander'),

-- Wheaton UC Upgrade (WTB_DEMO_008)
('WTB_DEMO_008', 'Site survey - Polycom assessment', 'Wheaton Branch - Conference Room UC Upgrade', 'site_survey', '501 N Main St, Wheaton, IL 60187', NOW() - INTERVAL '40 days', '9:00 AM', '11:00 AM', 'Mike Chen', 'completed', 'Documented 2 Polycom Group 500 systems. Both functional but EOL. Existing Cat6 runs are good. Mount points need adapter brackets for Cisco Room Bar.', 120, NOW() - INTERVAL '40 days', 'Mike Chen'),

-- Libertyville Training Room (WTB_DEMO_009)
('WTB_DEMO_009', 'Site survey - training room', 'Libertyville Branch - Training Room AV Refresh', 'site_survey', '1500 N Milwaukee Ave, Libertyville, IL 60048', NOW() - INTERVAL '73 days', '9:00 AM', '12:00 PM', 'Mike Chen', 'completed', 'Documented existing Epson projector and manual screen. Ceiling mount sturdy enough for 75in flat panel. Power at location. 3 network drops available.', 180, NOW() - INTERVAL '73 days', 'Mike Chen'),

-- Old Plank Trail TV Swap (WTB_DEMO_013)
('WTB_DEMO_013', 'On-site TV swap', 'Old Plank Trail Branch - Break Room TV Swap', 'service', '22001 S Wolf Rd, Mokena, IL 60448', NOW() - INTERVAL '10 days', '10:00 AM', '11:00 AM', 'Mike Chen', 'completed', 'Swapped dead 50in TV with spare from warehouse. Same mount, no modification needed. Old TV tagged for disposal.', 60, NOW() - INTERVAL '10 days', 'Mike Chen'),

-- 9700 Training Center Events (WTB_DEMO_014)
('WTB_DEMO_014', 'Q1 Leadership Town Hall (200 attendees)', '9700 Training Center - Q2 Event AV Support', 'event', '9700 W Higgins Rd, Rosemont, IL - 1F Multipurpose', NOW() - INTERVAL '28 days', '7:00 AM', '1:00 PM', 'Damon Alexander', 'completed', 'Full production setup: dual projectors on 16ft screens, 4 wireless lavs, 2 handhelds, Webex livestream to 3 remote offices. 200 in-room. Setup started 7am, event 9am-12pm, teardown by 1pm.', 360, NOW() - INTERVAL '28 days', 'Damon Alexander'),
('WTB_DEMO_014', 'New Hire Orientation (25 attendees)', '9700 Training Center - Q2 Event AV Support', 'event', '9700 W Higgins Rd, Rosemont, IL - 1F Room A', NOW() - INTERVAL '21 days', '8:30 AM', '12:00 PM', 'Mike Chen', 'completed', 'Standard classroom: projector, laptop connection, room audio. HR presented. No issues.', 210, NOW() - INTERVAL '21 days', 'Mike Chen'),
('WTB_DEMO_014', 'Board of Directors Meeting', '9700 Training Center - Q2 Event AV Support', 'event', '9700 W Higgins Rd, Rosemont, IL - 2F Executive Center', NOW() - INTERVAL '14 days', '6:00 AM', '2:00 PM', 'Damon Alexander', 'completed', 'High-security event. Setup at 6am. 4 remote board members via Webex. Backup Zoom tested. Full recording to cloud. IT Security present. No issues.', 480, NOW() - INTERVAL '14 days', 'Damon Alexander'),
('WTB_DEMO_014', 'Sales Training Workshop Day 1', '9700 Training Center - Q2 Event AV Support', 'event', '9700 W Higgins Rd, Rosemont, IL - 1F Room B+C combined', NOW() - INTERVAL '10 days', '8:00 AM', '5:00 PM', 'Mike Chen', 'completed', 'Combined Room B and C with movable wall. Portable PA system, 2 wireless mics. Breakout sessions used individual room systems. 35 attendees.', 540, NOW() - INTERVAL '10 days', 'Mike Chen'),
('WTB_DEMO_014', 'Sales Training Workshop Day 2', '9700 Training Center - Q2 Event AV Support', 'event', '9700 W Higgins Rd, Rosemont, IL - 1F Room B+C combined', NOW() - INTERVAL '9 days', '8:00 AM', '3:00 PM', 'Mike Chen', 'completed', 'Day 2 of workshop. Same setup. Afternoon breakout sessions. Teardown and reset rooms by 4pm.', 420, NOW() - INTERVAL '9 days', 'Mike Chen'),

-- Town Bank CRE Renovation (WTB_DEMO_015)
('WTB_DEMO_015', 'Walk through with CRE PM and GC', 'Town Bank Branch - CRE Renovation AV Coordination', 'cre_visit', '333 S Wacker Dr, Suite 200, Chicago, IL 60606 - 2nd Floor', NOW() - INTERVAL '7 days', '9:00 AM', '11:00 AM', 'Damon Alexander', 'completed', 'Met with CRE PM (Laura Chen) and Walsh Construction foreman. Identified: 4 desk monitors, 1 conference room Cisco system, 2 wall-mounted displays. All need disconnect before demo starts Monday.', 120, NOW() - INTERVAL '7 days', 'Damon Alexander'),
('WTB_DEMO_015', 'Document equipment locations and configs', 'Town Bank Branch - CRE Renovation AV Coordination', 'inspection', '333 S Wacker Dr, Suite 200, Chicago, IL 60606 - 2nd Floor', NOW() - INTERVAL '5 days', '9:00 AM', '12:00 PM', 'Mike Chen', 'completed', 'Photographed and documented all equipment positions, cable paths, IP configs. Created reconnection checklist for post-renovation.', 180, NOW() - INTERVAL '5 days', 'Mike Chen');

-- ============================================================
-- IN-PROGRESS (today)
-- ============================================================
INSERT INTO fieldops (project_id, task_name, project_name, type, location, scheduled_date, start_time, end_time, assignee, status, notes, estimated_duration) VALUES
('WTB_DEMO_005', 'Diversified on-site - display replacement', 'Hinsdale Branch - BreakFix: Boardroom Display Failure', 'service', '25 E 1st St, Hinsdale, IL 60521 - Main Boardroom', NOW(), '1:00 PM', '4:00 PM', 'Diversified (2 techs)', 'in-progress', 'Removing failed Samsung 75in (backlight failure). Mounting new Samsung QM75C. Diversified techs: Kevin and Matt. Branch manager aware, temp setup in smaller room.', 180);

-- ============================================================
-- SCHEDULED - Next 3 months
-- ============================================================
INSERT INTO fieldops (project_id, task_name, project_name, type, location, scheduled_date, start_time, end_time, assignee, status, notes, estimated_duration) VALUES
-- Tomorrow
('WTB_DEMO_005', 'Reconfigure Cisco codec with new display', 'Hinsdale Branch - BreakFix: Boardroom Display Failure', 'service', '25 E 1st St, Hinsdale, IL 60521 - Main Boardroom', NOW() + INTERVAL '1 day', '9:00 AM', '11:00 AM', 'Mike Chen', 'scheduled', 'After Diversified completes display swap. Verify HDMI handshake, update Cisco codec display settings, test all UC platforms.', 120),

-- This week
('WTB_DEMO_014', 'Client Investment Seminar', '9700 Training Center - Q2 Event AV Support', 'event', '9700 W Higgins Rd, Rosemont, IL - 2F Breakout 1', NOW() + INTERVAL '2 days', '8:00 AM', '12:00 PM', 'Damon Alexander', 'scheduled', 'Client-facing event for Wealth Management. Premium setup: branded presentation template on standby, lobby directional signage, bottled water. 30 external attendees. Suit required.', 240),
('WTB_DEMO_011', 'Lobby TV swap and test', 'Northbrook Branch - Lobby TV Replacement', 'service', '1200 Shermer Rd, Northbrook, IL 60062 - Main Lobby', NOW() + INTERVAL '3 days', '10:00 AM', '11:30 AM', 'Mike Chen', 'scheduled', 'Simple swap: remove cracked 55in, mount replacement (same model in stock). Verify HDMI from media player. Update signage content.', 90),

-- Next week
('WTB_DEMO_015', 'Disconnect and store AV for renovation', 'Town Bank Branch - CRE Renovation AV Coordination', 'cre_visit', '333 S Wacker Dr, Suite 200, Chicago, IL 60606 - 2nd Floor', NOW() + INTERVAL '4 days', '8:00 AM', '12:00 PM', 'Mike Chen', 'scheduled', 'GC (Walsh Construction) starts demolition Monday. All AV equipment must be disconnected, labeled, and stored in 1st floor storage closet by end of day Friday.', 240),
('WTB_DEMO_012', 'Disconnect AV for CRE ceiling repair', 'St. Charles Branch - CRE Repair: Conference Room B', 'cre_visit', '2020 Dean St, St. Charles, IL 60174 - Conf Room B', NOW() + INTERVAL '6 days', '9:00 AM', '10:30 AM', 'Mike Chen', 'scheduled', 'CRE contractor repairing damaged ceiling tile near projector mount and loose cable tray. Need to disconnect projector and move cable tray before they start.', 90),
('WTB_DEMO_006', 'Deploy Teams phones - Floor 1 (20 desks)', 'Lake Forest - Telephony Migration', 'installation', '700 N Western Ave, Lake Forest, IL 60045 - 1st Floor', NOW() + INTERVAL '6 days', '8:00 AM', '4:00 PM', 'Mike Chen', 'scheduled', 'Poly CCX400 deployment. Remove Cisco 7841 from each desk, connect CCX400, verify Teams sign-in, test inbound/outbound calls. 20 desks, ~20min each.', 480),
('WTB_DEMO_006', 'Network team - verify SBC config for Teams Direct Routing', 'Lake Forest - Telephony Migration', 'network', '700 N Western Ave, Lake Forest, IL 60045 - Server Room', NOW() + INTERVAL '5 days', '10:00 AM', '12:00 PM', 'Network Team (Jake Willis)', 'scheduled', 'Verify SBC (AudioCodes Mediant) configuration for Teams Direct Routing. Test inbound DID routing. Confirm E911 registration for all ported numbers.', 120),

-- Week after
('WTB_DEMO_014', 'IT Security Awareness Training (40 attendees)', '9700 Training Center - Q2 Event AV Support', 'event', '9700 W Higgins Rd, Rosemont, IL - 1F Room A', NOW() + INTERVAL '8 days', '9:00 AM', '11:00 AM', 'Mike Chen', 'scheduled', 'Standard classroom setup. IT Security team presenting. Laptop connection, room audio. ~40 attendees. No recording needed.', 120),
('WTB_DEMO_006', 'Deploy Teams phones - Floor 2 (25 desks)', 'Lake Forest - Telephony Migration', 'installation', '700 N Western Ave, Lake Forest, IL 60045 - 2nd Floor', NOW() + INTERVAL '9 days', '8:00 AM', '4:00 PM', 'Mike Chen', 'scheduled', 'Same process as Floor 1. 25 desks. CCX400 swap, Teams sign-in, call testing.', 480),
('WTB_DEMO_007', 'Digital signage installation (3 displays)', 'Crystal Lake - Digital Signage Deployment', 'installation', '100 W Virginia St, Crystal Lake, IL 60014 - Lobby and Teller Area', NOW() + INTERVAL '10 days', '9:00 AM', '1:00 PM', 'Mike Chen', 'scheduled', 'Mount 3 Samsung displays: 1 in main lobby (55in), 1 at teller counter (43in), 1 in waiting area (43in). Connect BrightSign media players. Configure FWI CMS.', 240),
('WTB_DEMO_012', 'Reconnect and test AV after ceiling repair', 'St. Charles Branch - CRE Repair: Conference Room B', 'service', '2020 Dean St, St. Charles, IL 60174 - Conf Room B', NOW() + INTERVAL '10 days', '9:00 AM', '11:00 AM', 'Mike Chen', 'scheduled', 'CRE repair should be complete. Reconnect projector, resecure cable tray, test video output, verify room fully operational.', 120),

-- Two weeks out
('WTB_DEMO_006', 'Teams Phone user training (3 sessions)', 'Lake Forest - Telephony Migration', 'training', '700 N Western Ave, Lake Forest, IL 60045 - Conference Room 1', NOW() + INTERVAL '13 days', '9:00 AM', '4:00 PM', 'Damon Alexander', 'scheduled', 'Three 1-hour sessions: 9am, 11am, 2pm. Cover: making/receiving calls, voicemail, transfer, conference, Teams app on mobile. Quick reference cards distributed.', 420),
('WTB_DEMO_004', 'CRE coordination - OAC Meeting #3', 'Schaumburg Branch - Conference Room Buildout', 'cre_visit', '1400 E Golf Rd, Schaumburg, IL 60173', NOW() + INTERVAL '4 days', '2:00 PM', '3:30 PM', 'Damon Alexander', 'scheduled', 'Pre-install coordination with Pepper Construction. Review: room readiness, dust-free status, equipment delivery dates, install window confirmation.', 90),
('WTB_DEMO_004', 'Pre-install inspection - verify rooms dust-free', 'Schaumburg Branch - Conference Room Buildout', 'inspection', '1400 E Golf Rd, Schaumburg, IL 60173', NOW() + INTERVAL '14 days', '9:00 AM', '11:00 AM', 'Mike Chen', 'scheduled', 'All 3 rooms must be dust-free (drywall, paint, carpet complete) before any AV equipment enters. This is a hard gate.', 120),
('WTB_DEMO_015', 'Reconnect conference room AV after renovation', 'Town Bank Branch - CRE Renovation AV Coordination', 'service', '333 S Wacker Dr, Suite 200, Chicago, IL 60606 - 2nd Floor', NOW() + INTERVAL '14 days', '9:00 AM', '1:00 PM', 'Mike Chen', 'scheduled', 'Walsh Construction should be done. Retrieve equipment from storage, reconnect per documentation checklist, test all systems.', 240),
('WTB_DEMO_014', 'Q2 All-Hands Town Hall (250+ attendees)', '9700 Training Center - Q2 Event AV Support', 'event', '9700 W Higgins Rd, Rosemont, IL - 1F Multipurpose', NOW() + INTERVAL '15 days', '7:00 AM', '1:00 PM', 'Damon Alexander', 'scheduled', 'Full production: dual projectors, 4 wireless mics, Webex livestream to 5 remote offices, cloud recording. CEO presenting. Setup 7am, doors 8:30am, event 9am-12pm.', 360),
('WTB_DEMO_004', 'Network team - VLAN and IP setup for 3 rooms', 'Schaumburg Branch - Conference Room Buildout', 'network', '1400 E Golf Rd, Schaumburg, IL 60173 - IDF', NOW() + INTERVAL '12 days', '9:00 AM', '12:00 PM', 'Network Team (Jake Willis)', 'scheduled', 'Configure AV VLAN on IDF switch for all 3 rooms. Assign IPs for: 3 Cisco/Neat endpoints, 3 displays, 1 Crestron processor. ISE MAC auth. Firewall policy group.', 180),

-- Three weeks out
('WTB_DEMO_004', 'AVI-SPL install - Room A (Cisco Room Kit Pro)', 'Schaumburg Branch - Conference Room Buildout', 'installation', '1400 E Golf Rd, Schaumburg, IL 60173 - Room A', NOW() + INTERVAL '20 days', '7:00 AM', '5:00 PM', 'AVI-SPL (3 techs)', 'scheduled', 'Room A: 12-seat. Dual 75in LG displays, Cisco Room Kit Pro, Crestron CP4 + DM NVX, 4-zone ceiling mic array. 2-day install, this is day 1.', 600),
('WTB_DEMO_004', 'AVI-SPL install - Room A Day 2 + Room B', 'Schaumburg Branch - Conference Room Buildout', 'installation', '1400 E Golf Rd, Schaumburg, IL 60173 - Room A+B', NOW() + INTERVAL '21 days', '7:00 AM', '5:00 PM', 'AVI-SPL (3 techs)', 'scheduled', 'Morning: finish Room A programming. Afternoon: Room B Teams MTR setup (65in display, Cisco Room Bar).', 600),
('WTB_DEMO_004', 'Whitlock install - Room C (Neat Bar)', 'Schaumburg Branch - Conference Room Buildout', 'installation', '1400 E Golf Rd, Schaumburg, IL 60173 - Room C', NOW() + INTERVAL '22 days', '9:00 AM', '1:00 PM', 'Whitlock Group (2 techs)', 'scheduled', 'Room C: 6-seat huddle. Neat Bar Pro, 55in display. Simple install, ~half day.', 240),
('WTB_DEMO_014', 'Wealth Management Client Dinner', '9700 Training Center - Q2 Event AV Support', 'event', '9700 W Higgins Rd, Rosemont, IL - 2F Executive Center', NOW() + INTERVAL '23 days', '3:00 PM', '9:00 PM', 'Damon Alexander', 'scheduled', 'Evening event. Background music via ceiling speakers, podium with wireless mic, projection for brief presentation. Low ambient lighting. 50 attendees. Formal dress.', 360),

-- Four weeks out
('WTB_DEMO_004', 'Commissioning - all 3 rooms', 'Schaumburg Branch - Conference Room Buildout', 'commissioning', '1400 E Golf Rd, Schaumburg, IL 60173', NOW() + INTERVAL '25 days', '9:00 AM', '4:00 PM', 'Damon Alexander', 'scheduled', 'Full commissioning: video (local + wireless share), audio (speaker + mic tuning), UC platforms (Webex, Teams, Zoom on each room), control system verification. Punch list created.', 420),
('WTB_DEMO_004', 'End-user training - branch staff', 'Schaumburg Branch - Conference Room Buildout', 'training', '1400 E Golf Rd, Schaumburg, IL 60173', NOW() + INTERVAL '28 days', '10:00 AM', '12:00 PM', 'Damon Alexander', 'scheduled', 'Train branch staff on all 3 room types. Hands-on with touch panel, wireless sharing, one-button join. Quick reference cards.', 120),

-- 5+ weeks out
('WTB_DEMO_014', 'Compliance Annual Review', '9700 Training Center - Q2 Event AV Support', 'event', '9700 W Higgins Rd, Rosemont, IL - 2F Breakout 1+2', NOW() + INTERVAL '37 days', '9:00 AM', '3:00 PM', 'Damon Alexander', 'scheduled', 'Combined breakout rooms with dividing wall open. Video playback system needed for compliance training videos. Recording required for audit trail. Legal team attending.', 360),
('WTB_DEMO_014', 'Summer Intern Orientation (20 interns)', '9700 Training Center - Q2 Event AV Support', 'event', '9700 W Higgins Rd, Rosemont, IL - 1F Room B', NOW() + INTERVAL '47 days', '9:00 AM', '12:00 PM', 'Mike Chen', 'scheduled', 'Standard classroom. HR and department heads presenting. Laptop connections, room audio. Photo op at end.', 180),
('WTB_DEMO_014', 'Executive Strategy Offsite Day 1', '9700 Training Center - Q2 Event AV Support', 'event', '9700 W Higgins Rd, Rosemont, IL - 2F Full (all spaces)', NOW() + INTERVAL '57 days', '7:00 AM', '6:00 PM', 'Damon Alexander', 'scheduled', 'All 2nd floor spaces reserved. Executive team only. Main session in Executive Center, breakout work in BR1+BR2. Catering coordination with facilities. Recording not permitted. Day 1 of 2.', 660),
('WTB_DEMO_014', 'Executive Strategy Offsite Day 2', '9700 Training Center - Q2 Event AV Support', 'event', '9700 W Higgins Rd, Rosemont, IL - 2F Full (all spaces)', NOW() + INTERVAL '58 days', '8:00 AM', '4:00 PM', 'Damon Alexander', 'scheduled', 'Day 2. Morning: breakout sessions. Afternoon: readout to full group in Executive Center. Teardown after 4pm.', 480);
